import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import type { SeoResult } from "@/sanity/types";
import { getSiteUrl, resolveRobots } from "./site";
import { routeUrl } from "./urls";

interface BuildMetadataArgs {
  seo: SeoResult;
  locale: string;
  /** Locale-independent route, e.g. "/" or "/for-partners". */
  href: string;
}

// One place that turns a Sanity seo object into Next metadata, so canonical
// and hreflang can never drift apart per route.
//
// hreflang is built from routing.locales rather than from a document lookup:
// for a fixed route the URL is already known in code, and deriving it from a
// translation-metadata document is how a canonical silently falls back to "/"
// when that document does not exist yet.
// The unfurl card, per language. Generated by scripts/og.ts from the home
// page's own headline and the jurisdiction labels, so it cannot disagree with
// the site; see that file for why it is a committed PNG rather than a runtime
// ImageResponse.
//
// One image per LANGUAGE and not one per page, deliberately. The page's own
// title sits directly beside the image in every unfurl, so a card repeating it
// spends the only picture the reader gets on something already on screen.
//
// It has to be repeated on every page that declares `openGraph`, because Next
// merges metadata shallowly: a child that sets openGraph replaces the parent's
// object whole, images included. Hence this helper rather than one entry in
// the layout.
export function ogImage(locale: string) {
  const siteUrl = getSiteUrl();
  const known = ["en", "ru", "pl"].includes(locale) ? locale : routing.defaultLocale;

  return {
    url: `${siteUrl}/og/${known}.png`,
    width: 1200,
    height: 630,
  };
}

export function buildMetadata({ seo, locale, href }: BuildMetadataArgs): Metadata {
  const languages = Object.fromEntries(routing.locales.map((l) => [l, routeUrl(href, l)]));

  return {
    title: seo.metaTitle,
    description: seo.metaDescription,
    robots: resolveRobots(seo.noIndex),
    alternates: {
      canonical: routeUrl(href, locale),
      languages: {
        ...languages,
        // Points at the unprefixed default so a search engine has somewhere
        // to send a visitor whose language matches none of the three.
        "x-default": routeUrl(href, routing.defaultLocale),
      },
    },
    openGraph: {
      title: seo.metaTitle,
      description: seo.metaDescription,
      url: routeUrl(href, locale),
      siteName: "moveandinvest",
      locale,
      type: "website",
      images: [ogImage(locale)],
    },
    // Written out rather than left to Next, which does not derive a Twitter
    // card from openGraph. Without `summary_large_image` the same picture is
    // cropped to a small square thumbnail.
    twitter: {
      card: "summary_large_image",
      title: seo.metaTitle,
      description: seo.metaDescription,
      images: [ogImage(locale).url],
    },
  };
}
