import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import type { SeoResult } from "@/sanity/types";
import { getSiteUrl, resolveRobots } from "./site";
import type { AppPathname } from "./routes";
import { routeUrl } from "./urls";

interface BuildMetadataArgs {
  seo: SeoResult;
  locale: string;
  /** Locale-independent route, e.g. "/" or "/for-partners". */
  href: AppPathname;
  /** ONE HREF PER LANGUAGE, for a page whose route differs by language because
   *  its slug lives in the dataset.
   *
   *  Omit it for a fixed route: those exist in code in all three languages, and
   *  deriving them from routing.locales is both correct and impossible to get
   *  out of sync. Pass it for a Guides & Research entry, whose Polish version
   *  has a slug of its own and may not have been written at all — a language
   *  absent from this map gets no hreflang rather than one pointing at a 404,
   *  which is the rule the jurisdiction pages already hold. */
  languages?: Record<string, AppPathname>;
}

// One place that turns a Sanity seo object into Next metadata, so canonical
// and hreflang can never drift apart per route.
//
// hreflang is built from routing.locales BY DEFAULT rather than from a document
// lookup: for a fixed route the URL is already known in code, and deriving it
// from a document is how a canonical silently falls back to "/" when that
// document does not exist yet. A caller whose slug genuinely differs per
// language passes `languages` and overrides that — see the field.
// The unfurl card, per language. Generated by scripts/og.ts from the home
// page's own headline and the jurisdiction labels, so it cannot disagree with
// the site; see that file for why it is a committed PNG rather than a runtime
// ImageResponse.
//
// One image per LANGUAGE and not one per page, deliberately. The page's own
// title sits directly beside the image in every unfurl, so a card repeating it
// spends the only picture the reader gets on something already on screen.
//
// It has to be repeated on every page that declares `openGraph`, because Next
// merges metadata shallowly: a child that sets openGraph replaces the parent's
// object whole, images included. Hence this helper rather than one entry in
// the layout.
export function ogImage(locale: string) {
  const siteUrl = getSiteUrl();
  const known = ["en", "ru", "pl"].includes(locale) ? locale : routing.defaultLocale;

  return {
    url: `${siteUrl}/og/${known}.png`,
    width: 1200,
    height: 630,
  };
}

export function buildMetadata({
  seo,
  locale,
  href,
  languages: perLanguage,
}: BuildMetadataArgs): Metadata {
  // A fixed route is the same route in every language, so its alternates are
  // derivable; a dataset-slugged page hands them in. The default covers the
  // first case and keeps every existing caller unchanged.
  const hrefs: Record<string, AppPathname> =
    perLanguage ?? Object.fromEntries(routing.locales.map((l) => [l, href]));

  const languages = Object.fromEntries(
    Object.entries(hrefs).map(([l, h]) => [l, routeUrl(h, l)]),
  );

  // Points at the unprefixed default so a search engine has somewhere to send a
  // visitor whose language matches none of the three. Only when the default
  // locale is actually among the alternates: for a fixed route it always is,
  // but an entry may exist in Russian and Polish and not in English, and an
  // x-default aimed at a page nobody wrote is worse than none.
  const fallback = hrefs[routing.defaultLocale];

  return {
    title: seo.metaTitle,
    description: seo.metaDescription,
    robots: resolveRobots(seo.noIndex),
    alternates: {
      canonical: routeUrl(href, locale),
      languages: {
        ...languages,
        ...(fallback
          ? { "x-default": routeUrl(fallback, routing.defaultLocale) }
          : {}),
      },
    },
    openGraph: {
      title: seo.metaTitle,
      description: seo.metaDescription,
      url: routeUrl(href, locale),
      siteName: "moveandinvest",
      locale,
      type: "website",
      images: [ogImage(locale)],
    },
    // Written out rather than left to Next, which does not derive a Twitter
    // card from openGraph. Without `summary_large_image` the same picture is
    // cropped to a small square thumbnail.
    twitter: {
      card: "summary_large_image",
      title: seo.metaTitle,
      description: seo.metaDescription,
      images: [ogImage(locale).url],
    },
  };
}
