// Regenerates src/components/country/JurisdictionCards/countryOutlines.ts.
//
// Not part of the build and not a dependency of the app: run it by hand when
// the set of jurisdictions changes, then commit the generated file.
//
//   cd scripts/geo
//   npm init -y && npm i world-atlas@2 topojson-client d3-geo
//   node outlines.mjs
//
// The three packages are deliberately NOT in the project's package.json. They
// are build-time cartography, used once per jurisdiction, and carrying them in
// the app's dependency tree for the sake of a file that changes twice a year
// is the wrong trade.

import fs from 'node:fs';
import * as topojson from 'topojson-client';
import { geoMercator, geoArea } from 'd3-geo';

// 1:10m, then Ramer–Douglas–Peucker in SCREEN space, per country. Simplifying
// the shared world topology instead flattens Malta (4km wide) to a lump while
// Greece is still over-detailed: the right tolerance is a fraction of a pixel
// in the card, not a fraction of a degree on the globe.
const topo = JSON.parse(fs.readFileSync('node_modules/world-atlas/countries-10m.json', 'utf8'));
const fc = topojson.feature(topo, topo.objects.countries);
const WANT = { Portugal: 'pt', Greece: 'gr', Malta: 'mt', 'United Arab Emirates': 'ae', Cyprus: 'cy' };
const TOL = 0.4; // px in the 200×140 card

const perp = (p, a, b) => {
  const dx = b[0] - a[0], dy = b[1] - a[1];
  const n = Math.hypot(dx, dy);
  if (n === 0) return Math.hypot(p[0] - a[0], p[1] - a[1]);
  return Math.abs(dy * p[0] - dx * p[1] + b[0] * a[1] - b[1] * a[0]) / n;
};
function rdp(pts, tol) {
  if (pts.length < 3) return pts;
  let max = 0, idx = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const d = perp(pts[i], pts[0], pts[pts.length - 1]);
    if (d > max) { max = d; idx = i; }
  }
  if (max <= tol) return [pts[0], pts[pts.length - 1]];
  return [...rdp(pts.slice(0, idx + 1), tol).slice(0, -1), ...rdp(pts.slice(idx), tol)];
}

const out = {};
for (const f of fc.features) {
  const code = WANT[f.properties.name];
  if (!code) continue;
  let geom = f.geometry;
  if (code === 'pt' && geom.type === 'MultiPolygon') {
    const biggest = geom.coordinates
      .map((c) => ({ c, a: geoArea({ type: 'Polygon', coordinates: c }) }))
      .sort((x, y) => y.a - x.a)[0].c;
    geom = { type: 'Polygon', coordinates: biggest };
  }
  const W = 200, H = 140, PAD = 6;
  const proj = geoMercator().fitExtent([[PAD, PAD], [W - PAD, H - PAD]], geom);
  const polys = geom.type === 'Polygon' ? [geom.coordinates] : geom.coordinates;

  let d = '';
  let kept = 0, total = 0, len = 0;
  for (const poly of polys) {
    for (const ring of poly) {
      const pts = ring.map((c) => proj(c)).filter(Boolean);
      total += pts.length;
      // Drop specks smaller than a hairline; they render as dirt, not islands.
      const xs = pts.map((p) => p[0]), ys = pts.map((p) => p[1]);
      if (Math.max(...xs) - Math.min(...xs) < 1 && Math.max(...ys) - Math.min(...ys) < 1) continue;
      const s = rdp(pts, TOL);
      if (s.length < 3) continue;
      kept += s.length;
      // Outline length, in the same 200×140 units as the path. Needed for the
      // stroke-dasharray that draws the shape, and computed here rather than
      // with getTotalLength() in the browser so the animation needs no
      // JavaScript at all — the number ships with the geometry.
      for (let i = 1; i < s.length; i++) len += Math.hypot(s[i][0] - s[i - 1][0], s[i][1] - s[i - 1][1]);
      len += Math.hypot(s[0][0] - s[s.length - 1][0], s[0][1] - s[s.length - 1][1]);
      d += 'M' + s.map((p) => `${p[0].toFixed(1)},${p[1].toFixed(1)}`).join('L') + 'Z';
    }
  }
  out[code] = { d, viewBox: `0 0 ${W} ${H}`, len: Math.round(len) };
  console.log(code, `${total} → ${kept} points`, `${(d.length / 1024).toFixed(1)}KB`, `length ${Math.round(len)}`);
}
const TS_HEADER = `// GENERATED by scripts/geo/outlines.mjs — do not hand-edit.
//
// One outline per jurisdiction, for the cards in section 03. Natural Earth
// 1:10m, projected per country with geoMercator().fitExtent into its own
// 200×140 box, then simplified with Ramer–Douglas–Peucker at a tolerance of
// 0.4 PIXELS — in screen space, not in degrees.
//
// The screen-space part is the whole trick. Simplifying the shared world
// topology instead applies one tolerance to the globe, which flattens Malta
// (316 km²) into a four-sided lump while Greece still carries six thousand
// points. Per country, per pixel, every outline lands at the same visual
// fidelity: 16 KB for all five.
//
// Each shape is fitted to its own box, so Malta renders as large as Portugal.
// That is deliberate — these are identifying marks, not a map — and the note
// under the section says so.

export interface CountryOutline {
  /** SVG path data, in the viewBox below. */
  d: string;
  viewBox: string;
  /** Total outline length in viewBox units — the stroke-dasharray that draws
   *  the shape. Computed here so nothing has to measure it in the browser. */
  len: number;
}

export const COUNTRY_OUTLINES: Record<string, CountryOutline> = {
`;

// Written in page order, so a diff of the generated file reads like the page.
const ORDER = ['pt', 'gr', 'mt', 'ae', 'cy'];
const body = ORDER.filter((k) => out[k])
  .map((k) => `  ${k}: {\n    d: "${out[k].d}",\n    viewBox: "${out[k].viewBox}",\n    len: ${out[k].len},\n  },`)
  .join('\n');

fs.writeFileSync(
  new URL('../../src/components/country/JurisdictionCards/countryOutlines.ts', import.meta.url),
  TS_HEADER + body + '\n};\n',
);
